export default {
    values: {},
    sizing: {},
    height: {},
    width: {},
    spacing: {},
    verticalPadding: {},
    horizontalPadding: {},
    itemSpacing: {},
    fill: {},
    stroke: {},
    borderRadius: {},
    borderRadiusTopLeft: {},
    borderRadiusTopRight: {},
    borderRadiusBottomRight: {},
    borderRadiusBottomLeft: {},
    borderWidth: {},
    opacity: {},
    fontFamilies: {},
    fontWeights: {},
    fontSizes: {},
    lineHeights: {},
    typography: {},
};
